"""add published_at to tech_items

Revision ID: 337debaadf4a
Revises: 4cc3362552c4
Create Date: 2026-05-28 09:29:12.855708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337debaadf4a'
down_revision: Union[str, Sequence[str], None] = '4cc3362552c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_items', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tech_items_published_at'), 'tech_items', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_items_published_at'), table_name='tech_items')
    op.drop_column('tech_items', 'published_at')
    # ### end Alembic commands ###
