"""add crawl_queue staging table

Revision ID: 4cc3362552c4
Revises: 67fb6c84eccc
Create Date: 2026-05-14 21:24:35.588890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc3362552c4'
down_revision: Union[str, Sequence[str], None] = '67fb6c84eccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_category', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_queue')
    # ### end Alembic commands ###
