"""add feed_events table

Revision ID: 64ffd26e3c14
Revises: b2bf64f7113d
Create Date: 2026-07-13 03:18:51.071564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ffd26e3c14'
down_revision: Union[str, Sequence[str], None] = 'b2bf64f7113d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_events',
    sa.Column('event_type', sa.Enum('Impression', 'Click', 'Dwell', name='feed_event_type'), nullable=False),
    sa.Column('tech_item_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tech_item_id'], ['tech_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_events_tech_item_id'), 'feed_events', ['tech_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_events_tech_item_id'), table_name='feed_events')
    op.drop_table('feed_events')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute(sa.text('DROP TYPE IF EXISTS feed_event_type'))
