"""add event layer tables

ARG-258 (Task 5 of the ARG-240 event layer): creates the four new tables —
``tech_events``, ``event_documents``, ``entities``, ``event_entities`` — in a
single revision. Splitting this across multiple revisions would break the
"downgrade -1 undoes the whole feature" acceptance criterion, since -1 only
reverts the most recent revision.

This revision is CREATE-only. ``tech_items`` is not touched by a single
``op.add_column`` / ``op.alter_column`` / ``op.drop_*`` — existing documents
keep their id and URL across an upgrade/downgrade round trip.

Table order in ``upgrade()`` respects FK dependencies: ``entities`` has no
dependency, ``tech_events`` only self-references (its ``merged_into_id`` FK is
declared inline in the same ``create_table`` — Postgres allows a FK to
reference the table currently being created), then ``event_documents``
(→ tech_events, tech_items) and ``event_entities`` (→ tech_events, entities).
``downgrade()`` drops in the exact reverse order, then drops the ``entity_kind``
enum type it created (precedent: revision 64ffd26e3c14's ``feed_event_type``
cleanup).

Revision ID: 855cb67b5096
Revises: 16778301d264
Create Date: 2026-08-18 17:05:30.227188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855cb67b5096'
down_revision: Union[str, Sequence[str], None] = '16778301d264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.Enum('Technology', 'Organization', 'Product', 'Person', 'Other', name='entity_kind'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_normalized_key'), 'entities', ['normalized_key'], unique=True)
    op.create_table('tech_events',
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('naming_stale', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['tech_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_events_merged_into_id'), 'tech_events', ['merged_into_id'], unique=False)
    op.create_table('event_documents',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tech_item_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['tech_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_item_id'], ['tech_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'tech_item_id', name='uq_event_documents_event_item')
    )
    op.create_index(op.f('ix_event_documents_event_id'), 'event_documents', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_documents_tech_item_id'), 'event_documents', ['tech_item_id'], unique=False)
    op.create_table('event_entities',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['tech_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'entity_id', name='uq_event_entities_event_entity')
    )
    op.create_index(op.f('ix_event_entities_entity_id'), 'event_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_entities_event_id'), 'event_entities', ['event_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping/recreating tech_items'
    # ix_tech_items_feed_score as a plain (non-DESC-NULLS-LAST) index here.
    # That is a known false positive — alembic's autogenerate cannot
    # introspect the `sa.text('feed_score DESC NULLS LAST')` expression index
    # created by revision 16778301d264, so it always diffs it against a plain
    # column index. tech_items must not be touched by this revision, so that
    # spurious drop/create pair was removed by hand.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_entities_event_id'), table_name='event_entities')
    op.drop_index(op.f('ix_event_entities_entity_id'), table_name='event_entities')
    op.drop_table('event_entities')
    op.drop_index(op.f('ix_event_documents_tech_item_id'), table_name='event_documents')
    op.drop_index(op.f('ix_event_documents_event_id'), table_name='event_documents')
    op.drop_table('event_documents')
    op.drop_index(op.f('ix_tech_events_merged_into_id'), table_name='tech_events')
    op.drop_table('tech_events')
    op.drop_index(op.f('ix_entities_normalized_key'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute(sa.text('DROP TYPE IF EXISTS entity_kind'))
