"""add trust_rubric and corroboration_count to tech_items

Revision ID: b2bf64f7113d
Revises: 5777c234802b
Create Date: 2026-07-12 03:24:37.856047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2bf64f7113d'
down_revision: Union[str, Sequence[str], None] = '5777c234802b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_items', sa.Column('trust_rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tech_items', sa.Column('corroboration_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tech_items', 'corroboration_count')
    op.drop_column('tech_items', 'trust_rubric')
    # ### end Alembic commands ###
